// Generated by gencpp from file planner_msgs/GoToGoal.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_GOTOGOAL_H
#define PLANNER_MSGS_MESSAGE_GOTOGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <planner_msgs/goal.h>

namespace planner_msgs
{
template <class ContainerAllocator>
struct GoToGoal_
{
  typedef GoToGoal_<ContainerAllocator> Type;

  GoToGoal_()
    : target()  {
    }
  GoToGoal_(const ContainerAllocator& _alloc)
    : target(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::planner_msgs::goal_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::planner_msgs::goal_<ContainerAllocator> >::other >  _target_type;
  _target_type target;




  typedef boost::shared_ptr< ::planner_msgs::GoToGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_msgs::GoToGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GoToGoal_

typedef ::planner_msgs::GoToGoal_<std::allocator<void> > GoToGoal;

typedef boost::shared_ptr< ::planner_msgs::GoToGoal > GoToGoalPtr;
typedef boost::shared_ptr< ::planner_msgs::GoToGoal const> GoToGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_msgs::GoToGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_msgs::GoToGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planner_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'planner_msgs': ['/home/pepper/AntBot/src/antbot/planner_msgs/msg', '/home/pepper/AntBot/devel/share/planner_msgs/msg', '/home/pepper/AntBot/src/antbot/planner_msgs/msg', '/home/pepper/AntBot/devel/share/planner_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::GoToGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::GoToGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::GoToGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::GoToGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::GoToGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::GoToGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_msgs::GoToGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c7eeba8aff53a215446e596e2937594";
  }

  static const char* value(const ::planner_msgs::GoToGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c7eeba8aff53a21ULL;
  static const uint64_t static_value2 = 0x5446e596e2937594ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_msgs::GoToGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_msgs/GoToGoal";
  }

  static const char* value(const ::planner_msgs::GoToGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_msgs::GoToGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
goal[] target\n\
\n\
================================================================================\n\
MSG: planner_msgs/goal\n\
# Position \n\
geometry_msgs/Pose2D pose\n\
# Desired speed\n\
float32 speed\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::planner_msgs::GoToGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_msgs::GoToGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_msgs::GoToGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_msgs::GoToGoal_<ContainerAllocator>& v)
  {
    s << indent << "target[]" << std::endl;
    for (size_t i = 0; i < v.target.size(); ++i)
    {
      s << indent << "  target[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::planner_msgs::goal_<ContainerAllocator> >::stream(s, indent + "    ", v.target[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_GOTOGOAL_H
