// Generated by gencpp from file planner_msgs/GoToResult.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_GOTORESULT_H
#define PLANNER_MSGS_MESSAGE_GOTORESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner_msgs
{
template <class ContainerAllocator>
struct GoToResult_
{
  typedef GoToResult_<ContainerAllocator> Type;

  GoToResult_()
    : route_result(0)  {
    }
  GoToResult_(const ContainerAllocator& _alloc)
    : route_result(0)  {
  (void)_alloc;
    }



   typedef int32_t _route_result_type;
  _route_result_type route_result;




  typedef boost::shared_ptr< ::planner_msgs::GoToResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_msgs::GoToResult_<ContainerAllocator> const> ConstPtr;

}; // struct GoToResult_

typedef ::planner_msgs::GoToResult_<std::allocator<void> > GoToResult;

typedef boost::shared_ptr< ::planner_msgs::GoToResult > GoToResultPtr;
typedef boost::shared_ptr< ::planner_msgs::GoToResult const> GoToResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_msgs::GoToResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_msgs::GoToResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planner_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'planner_msgs': ['/home/pepper/AntBot/src/antbot/planner_msgs/msg', '/home/pepper/AntBot/devel/share/planner_msgs/msg', '/home/pepper/AntBot/src/antbot/planner_msgs/msg', '/home/pepper/AntBot/devel/share/planner_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::GoToResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::GoToResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::GoToResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::GoToResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::GoToResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::GoToResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_msgs::GoToResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69ac0a96c2c117c85b1bb21cd0b855f1";
  }

  static const char* value(const ::planner_msgs::GoToResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69ac0a96c2c117c8ULL;
  static const uint64_t static_value2 = 0x5b1bb21cd0b855f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_msgs::GoToResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_msgs/GoToResult";
  }

  static const char* value(const ::planner_msgs::GoToResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_msgs::GoToResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
int32 route_result\n\
";
  }

  static const char* value(const ::planner_msgs::GoToResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_msgs::GoToResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.route_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_msgs::GoToResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_msgs::GoToResult_<ContainerAllocator>& v)
  {
    s << indent << "route_result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.route_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_GOTORESULT_H
