#!/usr/bin/python
# -*- coding: UTF-8 -*-
from Tkinter import *       # 导入 Tkinter 库
#from ttk import *           # 导入 Tkinter 库
import thread
import time
import os
class MessageShow:
	def __init__(self):	
		
		#传入参数　消息内容　和这条消息显示的时间
		
		#消息显示的时间
		#self.WaitTime=time
		self.root = Tk()                     # 创建窗口对象的背景色
		self.root.wm_title("机器人控制主窗口")#title
		#居中显示
		self.root.resizable(False,False)
		self.root.update() # update window ,must do
		curWidth = self.root.winfo_reqwidth() # get current width
		curHeight = self.root.winfo_height() # get current height
		scnWidth,scnHeight = self.root.maxsize() # get screen width and height
		#tmpcnf = '%dx%d+%d+%d'%(100,600,(scnWidth-curWidth)/2,(scnHeight-curHeight)/2)
		tmpcnf = '%dx%d+%d+%d'%(300,440,10,10)#width heigh start_x, start_y
		self.root.geometry(tmpcnf)
		
		#l1=Label(self.root,text=message,background="yellow")
		#font=("宋体", 12, "normal")
		#l1=Label(self.root,text=message,foreground="red")
		#l1.pack(side=TOP,expand=YES)
		
		#按键添加如下
		self.b1=Button(self.root,text="fake_antbot",height=2,command=self.b1Command).pack(fill=X)
		self.b2=Button(self.root,text="map_server",height=2,command=self.b2Command).pack(fill=X)
		self.b3=Button(self.root,text="purepursuit",height=2,command=self.b3Command).pack(fill=X)
		self.b4=Button(self.root,text="purepursuit_maker",height=2,command=self.b4Command).pack(fill=X)
		self.quit=Button(self.root,text="退出",height=2,command=self.autoDestory).pack(fill=X)
		
		#thread.start_new_thread(self.autoDestory,())
		self.root.mainloop()                 # 进入消息循环
	def b1Command(self):
		os.system("gnome-terminal -x bash -c \"roslaunch antbot_bringup fake_antbot_without_rviz.launch --screen\"")
		self.b1['bg']='red'
	def b2Command(self):
		os.system("gnome-terminal -x bash -c \"roslaunch antbot_navigation fake_map_server_2.launch\"")
	def b3Command(self):
		os.system("gnome-terminal -x bash -c \"roslaunch purepursuit_planner purepursuit_2.launch\"")
	def b4Command(self):
		os.system("gnome-terminal -x bash -c \"roslaunch purepursuit_planner purepursuit_marker.launch\"")
	def b5Command(self):
		os.system("gnome-terminal -x bash -c \"rosrun map_server map_saver -f antbot\"")
	def autoDestory(self):
		self.root.destroy()
if __name__=='__main__':
	MessageShow()
	
